configuration:
  base: root
  target: local
  basePath: /var/tmp/
  resultsPath: /results/
  dataSubPath: /data/data_small/
  mpiParameters:
    schema: MpiViSchema01
    comInterval: 1
    maxIterations: 1000
    conditionThreshold: 5
  viParameters:
    doAsync: false
    alpha: 0.99
    eps: 1e-6
    maxIterations: 5
    conditionThreshold: 2
    numThreads: 2
