@startuml
'left to right direction
' Horizontal lines: -->, <--, <-->'
title SCHEME 4
start
:<size:18><i><b>LOAD DATA</b></i></size>;
repeat
   :rank_0/
   :MPI_Bcast(J)|
fork
    :rank_0/
:<size:15><i><b>Value Iteration</b></i></size>;
fork again
    :rank_N/
:<size:15><i><b>Value Iteration</b></i></size>;
end fork
:rank_0/
:MPI_Igatherv(J)|
:MPI_Test|
repeat while (eps < eps_thresh) is (No) not (Yes)
:MPI_Gatherv(Pi)|

stop

@enduml