@startuml
'left to right direction
' Horizontal lines: -->, <--, <-->'
title SCHEME 1
start
:<size:18><i><b>LOAD DATA</b></i></size>;
fork
    :rank_0/
repeat
    :<size:15><i><b>Value Iteration</b></i></size>;
    :MPI_Allgatherv(J)|
    :MPI_Allreduce(eps)|
repeat while (eps < eps_thresh) is (No) not (Yes)
fork again
    :rank_N/
repeat
    :<size:15><i><b>Value Iteration</b></i></size>;
    :MPI_Allgatherv(J)|
    :MPI_Allreduce(eps)|
repeat while (eps < eps_thresh) is (No) not (Yes)
end fork
:MPI_Gatherv(Pi)|
stop

@enduml