@startuml
'left to right direction
' Horizontal lines: -->, <--, <-->'
title SCHEME 3
start
fork
    :rank_0/
    :read data;
fork again
    :rank_N/
    :read data;
end fork
repeat
    :MPI_Bcast(J)|
fork
repeat
    backward:nIteration;
    repeat while (value Iteration)
    :MPI_ISEND(J)|
fork again
repeat
    backward:nIteration;
    repeat while (value Iteration)
    :MPI_ISEND(J)|
end fork
:rank_0/
repeat while (eps < eps_thresh) is (No) not (Yes)
:MPI_Gatherv(Pi)|

stop

@enduml